-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 00:24:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bxnqelfbn7laqx7u4inv
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bxnqelfbn7laqx7u4inv` ;

-- -----------------------------------------------------
-- Schema bxnqelfbn7laqx7u4inv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bxnqelfbn7laqx7u4inv` DEFAULT CHARACTER SET utf8 ;
USE `bxnqelfbn7laqx7u4inv` ;

-- -----------------------------------------------------
-- Table `bxnqelfbn7laqx7u4inv`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bxnqelfbn7laqx7u4inv`.`experiencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcione` VARCHAR(255) NULL DEFAULT NULL,
  `nombree` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bxnqelfbn7laqx7u4inv`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bxnqelfbn7laqx7u4inv`.`persona` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bxnqelfbn7laqx7u4inv`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bxnqelfbn7laqx7u4inv`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol_nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bxnqelfbn7laqx7u4inv`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bxnqelfbn7laqx7u4inv`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `nombre_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `UK_puhr3k3l7bj71hb7hk7ktpxn0` ON `bxnqelfbn7laqx7u4inv`.`usuario` (`nombre_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bxnqelfbn7laqx7u4inv`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bxnqelfbn7laqx7u4inv`.`usuario_rol` (
  `usuario_id` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id`, `rol_id`),
  CONSTRAINT `FK610kvhkwcqk2pxeewur4l7bd1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `bxnqelfbn7laqx7u4inv`.`rol` (`id`),
  CONSTRAINT `FKbyfgloj439r9wr9smrms9u33r`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bxnqelfbn7laqx7u4inv`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK610kvhkwcqk2pxeewur4l7bd1` ON `bxnqelfbn7laqx7u4inv`.`usuario_rol` (`rol_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
